=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_C4_ScionsOfDestiny/dist/game/data/xsd/multisell.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="0">
				<xs:element maxOccurs="unbounded" name="item">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element maxOccurs="unbounded" name="ingredient">
									<xs:complexType>
										<xs:attribute name="id" type="xs:unsignedShort" use="required" />
										<xs:attribute name="count" type="xs:unsignedInt" use="required" />
										<xs:attribute name="isTaxIngredient" type="xs:boolean" use="optional" />
										<xs:attribute name="mantainIngredient" type="xs:boolean" use="optional" />
										<xs:attribute name="enchantmentLevel" type="xs:unsignedByte" use="optional" />
									</xs:complexType>
								</xs:element>
								<xs:element name="production">
									<xs:complexType>
										<xs:attribute name="id" type="xs:unsignedShort" use="required" />
										<xs:attribute name="count" type="xs:unsignedInt" use="required" />
										<xs:attribute name="enchantmentLevel" type="xs:unsignedByte" use="optional" />
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedShort" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="maintainEnchantment" type="xs:boolean" use="optional" />
			<xs:attribute name="applyTaxes" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_07.0_PreludeOfWar/dist/game/data/multisell/839.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<npcs>
		<npc>33587</npc> <!-- Mentor Guide -->
	</npcs>
	<!-- TODO: Part 3
	<item>
		<ingredient id="33804" count="100000" /> --> <!-- Mentee's Mark --> 
	<!-- <production id="48937" count="1" /> --> <!-- Atlas' Earring --> 
	<!-- </item> -->
	<!-- TODO: Part 3
	<item>
		<ingredient id="33804" count="10000" /> --> <!-- Mentee's Mark --> 
	<!-- <production id="48937" count="1" /> --> <!-- Mask Expert's --> 
	<!-- </item> -->
	<!-- TODO: Part 3
	<item>
		<ingredient id="33804" count="10000" /> --> <!-- Mentee's Mark --> 
	<!-- <production id="48937" count="1" /> --> <!-- Scroll: Enchant Expert's Mask --> 
	<!-- </item> -->
	<item>
		<ingredient id="33804" count="5000" /> <!-- Mentee's Mark --> 
		<production id="48848" count="1" /> <!-- Freya's Ice Rose - Event --> 
	</item>
	<item>
		<ingredient id="33804" count="8000" /> <!-- Mentee's Mark --> 
		<production id="80832" count="1" /> <!-- Emperor's Special Cocktail Event --> 
	</item>
	<item>
		<ingredient id="33804" count="5000" /> <!-- Mentee's Mark --> 
		<!-- TODO: Swap on Event item -->
		<production id="80842" count="1" /> <!-- Honey Dark Beer Event --> 
	</item>
	<item>
		<ingredient id="33804" count="5000" /> <!-- Mentee's Mark --> 
		<production id="48755" count="1" /> <!-- Glowing Dragon's Attribute Potion (XP) Event --> 
	</item>
	<item>
		<ingredient id="33804" count="20000" /> <!-- Mentee's Mark --> 
		<production id="80797" count="1" /> <!-- Shining Nevit's Gold Hourglass Event --> 
	</item>
	<!-- TODO: Part 3
	<item>
		<ingredient id="33804" count="5000" /> --> <!-- Mentee's Mark --> 
		<!-- <production id="33870" count="1" /> --> <!-- Blessed Scroll: Enchant Bracelet --> 
	<!-- </item> -->
	<item>
		<ingredient id="33804" count="20000" /> <!-- Mentee's Mark --> 
		<production id="48498" count="1" /> <!-- Blessed Scroll: Enchant Dragon Shirt --> 
	</item>
	<!-- TODO: Part 3
	<item>
		<ingredient id="33804" count="45000" /> --> <!-- Mentee's Mark --> 
		<!-- <production id="33872" count="1" /> --> <!-- Blessed Scroll: Enchant Circlet --> 
	<!-- </item> -->
	<!-- TODO: Part 3
	<item>
		<ingredient id="33804" count="100000" /> --> <!-- Mentee's Mark --> 
		<!-- <production id="33873" count="1" /> --> <!-- Shining Platinum Jewelry --> 
	<!-- </item> -->
	<item>
		<ingredient id="33804" count="50000" /> <!-- Mentee's Mark --> 
		<production id="48124" count="1" /> <!-- Fairy Agathion Charm --> 
	</item>
</list>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_10.0_MasterClass/dist/game/data/multisell/929.xml
<?xml version="1.0" encoding="UTF-8"?>
<list maintainEnchantment="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<npcs>
		<npc>30298</npc> <!-- Pinter -->
		<npc>30300</npc> <!-- Pushkin -->
		<npc>30317</npc> <!-- Kluto -->
		<npc>30458</npc> <!-- Poitan -->
		<npc>30471</npc> <!-- Rupio -->
		<npc>30678</npc> <!-- Helton -->
		<npc>30688</npc> <!-- Duning -->
		<npc>30846</npc> <!-- Wilbert -->
		<npc>30898</npc> <!-- Morning -->
		<npc>31271</npc> <!-- Hilda -->
		<npc>31316</npc> <!-- Vincenz -->
		<npc>31583</npc> <!-- Feynn -->
		<npc>31960</npc> <!-- Buryun -->
		<npc>31990</npc> <!-- Siger -->
		<npc>33998</npc> <!-- Momet -->
		<npc>34208</npc> <!-- Bartman -->
	</npcs>
	<item>
		<ingredient id="80090" count="1" /> <!-- Krishna Shaper -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80133" count="1" /> <!-- Enhanced Krishna Shaper -->
	</item>
	<item>
		<ingredient id="80091" count="1" /> <!-- Krishna Cutter -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80134" count="1" /> <!-- Enhanced Krishna Shaper -->
	</item>
	<item>
		<ingredient id="80092" count="1" /> <!-- Krishna Slashe -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80135" count="1" /> <!-- Enhanced Krishna Slashe -->
	</item>
	<item>
		<ingredient id="80093" count="1" /> <!-- Krishna Avenger -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80136" count="1" /> <!-- Enhanced Krishna Avenger -->
	</item>
	<item>
		<ingredient id="80094" count="1" /> <!-- Krishna Fighter -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80137" count="1" /> <!-- Enhanced Krishna Fighter -->
	</item>
	<item>
		<ingredient id="80095" count="1" /> <!-- Krishna Stormer -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80138" count="1" /> <!-- Enhanced Krishna Stormer -->
	</item>
	<item>
		<ingredient id="80096" count="1" /> <!-- Krishna Krishna Thrower -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80139" count="1" /> <!-- Enhanced Krishna Thrower -->
	</item>
	<item>
		<ingredient id="80097" count="1" /> <!-- Krishna Shooter -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80140" count="1" /> <!-- Enhanced Krishna Shooter -->
	</item>
	<item>
		<ingredient id="80098" count="1" /> <!-- Krishna Buster -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80141" count="1" /> <!-- Enhanced Krishna Buster -->
	</item>
	<item>
		<ingredient id="80099" count="1" /> <!-- Krishna Caster -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80142" count="1" /> <!-- Enhanced Krishna Caster -->
	</item>
	<item>
		<ingredient id="80100" count="1" /> <!-- Krishna Retributer -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80143" count="1" /> <!-- Enhanced Krishna Retributer -->
	</item>
	<item>
		<ingredient id="80101" count="1" /> <!-- Krishna Dual Sword -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80144" count="1" /> <!-- Enhanced Krishna Dual Sword -->
	</item>
	<item>
		<ingredient id="80102" count="1" /> <!-- Krishna Dual Dagger -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80145" count="1" /> <!-- Enhanced Krishna Dual Dagger -->
	</item>
	<item>
		<ingredient id="80103" count="1" /> <!-- Krishna Dual Blunt Weapon -->
		<ingredient id="19440" count="1406" /> <!-- R-grade Gemstone -->
		<ingredient id="36515" count="7700" /> <!-- Elcyum -->
		<ingredient id="57" count="5058112338" /> <!-- Adena -->
		<production id="80146" count="1" /> <!-- Enhanced Krishna Dual Blunt Weapon -->
	</item>
</list>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_09.2_ReturnOfTheQueenAnt/dist/game/data/multisell/custom/700004.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/multisell.xsd">
	<npcs>
		<npc>-1</npc> <!-- CB -->
	</npcs>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Dark Crystal Heavy -->
		<production count="1" id="365" />
		<production count="1" id="512" />
		<production count="1" id="388" />
		<production count="1" id="5765" />
		<production count="1" id="5777" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Dark Crystal Light -->
		<production count="1" id="2385" />
		<production count="1" id="512" />
		<production count="1" id="2389" />
		<production count="1" id="5766" />
		<production count="1" id="5778" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Dark Crystal Robe -->
		<production count="1" id="2407" />
		<production count="1" id="512" />
		<production count="1" id="5767" />
		<production count="1" id="5779" />
	</item>
	<item>
		<ingredient count="3000000" id="57" />
		<!-- Dark Crystal Shield -->
		<production count="1" id="641" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Tallum Heavy -->
		<production count="1" id="2382" />
		<production count="1" id="547" />
		<production count="1" id="5768" />
		<production count="1" id="5780" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Tallum Light -->
		<production count="1" id="2393" />
		<production count="1" id="547" />
		<production count="1" id="5769" />
		<production count="1" id="5781" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Tallum Robe -->
		<production count="1" id="2400" />
		<production count="1" id="547" />
		<production count="1" id="2405" />
		<production count="1" id="5770" />
		<production count="1" id="5782" />
	</item>
	<item>
		<ingredient count="6773000" id="57" />
		<!-- Nightmare Heavy -->
		<production count="1" id="374" />
		<production count="1" id="2418" />
		<production count="1" id="5771" />
		<production count="1" id="5783" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Nightmare Light -->
		<production count="1" id="2394" />
		<production count="1" id="2418" />
		<production count="1" id="5772" />
		<production count="1" id="5784" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Nightmare Robe -->
		<production count="1" id="2408" />
		<production count="1" id="2418" />
		<production count="1" id="5773" />
		<production count="1" id="5785" />
	</item>
	<item>
		<ingredient count="3000000" id="57" />
		<!-- Nightmare Shield -->
		<production count="1" id="2498" />
	</item>
	<item>
		<ingredient count="6773000" id="57" />
		<!-- Majestic Heavy -->
		<production count="1" id="2383" />
		<production count="1" id="2419" />
		<production count="1" id="5774" />
		<production count="1" id="5786" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Majestic Light -->
		<production count="1" id="2395" />
		<production count="1" id="2419" />
		<production count="1" id="5775" />
		<production count="1" id="5787" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Majestic Robe -->
		<production count="1" id="2409" />
		<production count="1" id="2419" />
		<production count="1" id="5776" />
		<production count="1" id="5788" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Apella Heavy -->
		<production count="1" id="7861" />
		<production count="1" id="7860" />
		<production count="1" id="7862" />
		<production count="1" id="7863" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Apella Light -->
		<production count="1" id="7864" />
		<production count="1" id="7860" />
		<production count="1" id="7865" />
		<production count="1" id="7866" />
	</item>
	<item>
		<ingredient count="6000000" id="57" />
		<!-- Apella Robe -->
		<production count="1" id="7867" />
		<production count="1" id="7860" />
		<production count="1" id="7868" />
		<production count="1" id="7869" />
	</item>
</list>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_10.0_MasterClass/dist/game/data/multisell/2039.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<npcs>
		<npc>33872</npc> <!-- Jenna -->
	</npcs>
	<item>
		<ingredient id="36434" count="1" /> <!-- Lindvior Shaper - Fragment --> 
		<ingredient id="36414" count="50" /> <!-- Dragon Claw --> 
		<!-- Elcyum -->
		<ingredient count="500" id="36515" />
		<!-- Giant's Energy -->
		<ingredient count="800" id="35563" />
		<!-- Gemstone (R-Grade) -->
		<ingredient count="105800" id="19440" />
		<production id="36458" count="1" /> <!-- Lindvior Shaper - Standard --> 
	</item>
	<item>
		<ingredient id="36435" count="1" /> <!-- Lindvior Thrower - Fragment --> 
		<ingredient id="36414" count="50" /> <!-- Dragon Claw --> 
		<!-- Elcyum -->
		<ingredient count="500" id="36515" />
		<!-- Giant's Energy -->
		<ingredient count="800" id="35563" />
		<!-- Gemstone (R-Grade) -->
		<ingredient count="105800" id="19440" />
		<production id="36459" count="1" /> <!-- Lindvior Thrower - Standard --> 
	</item>
	<item>
		<ingredient id="36436" count="1" /> <!-- Lindvior Slasher - Fragment --> 
		<ingredient id="36414" count="50" /> <!-- Dragon Claw --> 
		<!-- Elcyum -->
		<ingredient count="500" id="36515" />
		<!-- Giant's Energy -->
		<ingredient count="800" id="35563" />
		<!-- Gemstone (R-Grade) -->
		<ingredient count="105800" id="19440" />
		<production id="36460" count="1" /> <!-- Lindvior Slasher - Standard --> 
	</item>
	<item>
		<ingredient id="36437" count="1" /> <!-- Lindvior Caster - Fragment --> 
		<ingredient id="36414" count="50" /> <!-- Dragon Claw --> 
		<!-- Elcyum -->
		<ingredient count="500" id="36515" />
		<!-- Giant's Energy -->
		<ingredient count="800" id="35563" />
		<!-- Gemstone (R-Grade) -->
		<ingredient count="105800" id="19440" />
		<production id="36461" count="1" /> <!-- Lindvior Caster - Standard --> 
	</item>
	<item>
		<ingredient id="36438" count="1" /> <!-- Lindvior Cutter - Fragment --> 
		<ingredient id="36414" count="50" /> <!-- Dragon Claw --> 
		<!-- Elcyum -->
		<ingredient count="500" id="36515" />
		<!-- Giant's Energy -->
		<ingredient count="800" id="35563" />
		<!-- Gemstone (R-Grade) -->
		<ingredient count="105800" id="19440" />
		<production id="36462" count="1" /> <!-- Lindvior Cutter - Standard --> 
	</item>
	<item>
		<ingredient id="36439" count="1" /> <!-- Lindvior Shooter - Fragment --> 
		<ingredient id="36414" count="50" /> <!-- Dragon Claw --> 
		<!-- Elcyum -->
		<ingredient count="500" id="36515" />
		<!-- Giant's Energy -->
		<ingredient count="800" id="35563" />
		<!-- Gemstone (R-Grade) -->
		<ingredient count="105800" id="19440" />
		<production id="36463" count="1" /> <!-- Lindvior Shooter - Standard --> 
	</item>
	<item>
		<ingredient id="36440" count="1" /> <!-- Lindvior Dual Dagger - Fragment --> 
		<ingredient id="36414" count="50" /> <!-- Dragon Claw --> 
		<!-- Elcyum -->
		<ingredient count="500" id="36515" />
		<!-- Giant's Energy -->
		<ingredient count="800" id="35563" />
		<!-- Gemstone (R-Grade) -->
		<ingredient count="105800" id="19440" />
		<production id="36464" count="1" /> <!-- Lindvior Dual Dagger - Standard --> 
	</item>
</list>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_Essence_6.0_BattleChronicle/dist/game/data/multisell/3084104.xml
<?xml version="1.0" encoding="UTF-8"?>
<list maintainEnchantment="false" isChanceMultisell="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<npcs>
		<npc>30841</npc> <!-- Carson -->
	</npcs>
	<item>
		<ingredient id="93974" count="1" /> <!-- Best Dye Coupon --> 
		<production id="93968" count="1" chance="100" /> <!-- Best Dye of STR <STR +3> 3rd class class --> 
	</item>
	<item>
		<ingredient id="93974" count="1" /> <!-- Best Dye Coupon --> 
		<production id="93969" count="1" chance="100" /> <!-- Best Dye of CON <CON +3> 3rd class class --> 
	</item>
	<item>
		<ingredient id="93974" count="1" /> <!-- Best Dye Coupon --> 
		<production id="93970" count="1" chance="100" /> <!-- Best Dye of DEX <DEX +3> 3rd class class --> 
	</item>
	<item>
		<ingredient id="93974" count="1" /> <!-- Best Dye Coupon --> 
		<production id="93971" count="1" chance="100" /> <!-- Best Dye of INT <INT +3> 3rd class class --> 
	</item>
	<item>
		<ingredient id="93974" count="1" /> <!-- Best Dye Coupon --> 
		<production id="93972" count="1" chance="100" /> <!-- Best Dye of MEN <MEN +3> 3rd class class --> 
	</item>
	<item>
		<ingredient id="93974" count="1" /> <!-- Best Dye Coupon --> 
		<production id="93973" count="1" chance="100" /> <!-- Best Dye of WIT <WIT +3> 3rd class class --> 
	</item>
</list>
