=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_Essence_6.0_BattleChronicle/dist/game/data/xsd/items.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="item">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element maxOccurs="unbounded" name="set">
									<xs:complexType>
										<xs:attribute name="name" type="xs:string" use="required" />
										<xs:attribute name="val" type="xs:string" use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element name="skills">
									<xs:complexType>
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="skill">
												<xs:complexType>
													<xs:attribute name="id" type="xs:unsignedShort" use="required" />
													<xs:attribute name="level" type="xs:unsignedByte" use="required" />
													<xs:attribute name="type" type="xs:string" use="optional" />
													<xs:attribute name="type_value" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="type_chance" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="stats">
									<xs:complexType>
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="stat">
												<xs:complexType>
													<xs:simpleContent>
														<xs:extension base="xs:decimal">
															<xs:attribute name="type" type="xs:string" use="required" />
														</xs:extension>
													</xs:simpleContent>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="cond">
									<xs:complexType>
										<xs:sequence>
											<xs:element minOccurs="0" name="target">
												<xs:complexType>
													<xs:attribute name="levelRange" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="and">
												<xs:complexType>
													<xs:sequence>
														<xs:element maxOccurs="unbounded" name="player">
															<xs:complexType>
																<xs:attribute name="castle" type="xs:byte" use="optional" />
																<xs:attribute name="pledgeClass" type="xs:byte" use="optional" />
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="player">
												<xs:complexType>
													<xs:attribute name="flyMounted" type="xs:boolean" use="optional" />
													<xs:attribute name="isHero" type="xs:boolean" use="optional" />
													<xs:attribute name="sex" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="level" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="chaotic" type="xs:boolean" use="optional" />
													<xs:attribute name="levelRange" type="xs:string" use="optional" />
													<xs:attribute name="insideZoneId" type="xs:string" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="addName" type="xs:unsignedByte" use="optional" />
										<xs:attribute name="msgId" type="xs:unsignedShort" use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element name="capsuled_items">
									<xs:complexType mixed="true">
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="item">
												<xs:complexType>
													<xs:attribute name="id" type="xs:unsignedInt" use="required" />
													<xs:attribute name="min" type="xs:unsignedInt" use="required" />
													<xs:attribute name="max" type="xs:unsignedInt" use="required" />
													<xs:attribute name="chance" type="xs:decimal" use="required" />
													<xs:attribute name="minEnchant" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="maxEnchant" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedInt" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="type" type="xs:string" use="required" />
						<xs:attribute name="additionalName" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_Essence_6.0_BattleChronicle/dist/game/data/stats/items/99000-99099.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="99026" name="Christmas Cube (Time-limited)" additionalName="Sealed" type="EtcItem">
		<!-- Double-click to obtain Christmas Sack. -->
		<set name="icon" val="icon.etc_11th_event_group" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
	</item>
	<item id="99027" name="Daily Present - VIP 8" type="EtcItem">
		<!-- Double-click the item to receive 1 Blessed Scroll of Escape, 1 Blessed Scroll of Resurrection, 3 Greater Healing Potions, 150 VIP Coins. -->
		<set name="icon" val="BranchIcon.Icon.etc_vip_present_i06" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="FISH" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="extractableCountMin" val="3" />
		<set name="extractableCountMax" val="3" />
		<capsuled_items>
			<item id="91689" min="1" max="1" chance="100.00" /> <!-- Blessed Scroll of Escape -->
			<item id="3936" min="1" max="1" chance="100.00" /> <!-- Blessed Scroll of Resurrection -->
			<item id="29652" min="3" max="3" chance="100.00" /> <!-- Major Healing Potion -->
		</capsuled_items>
	</item>
	<item id="99028" name="Daily Present - VIP 9" type="EtcItem">
		<!-- Double-click the item to receive 1 Blessed Scroll of Escape, 1 Blessed Scroll of Resurrection, 3 Greater Healing Potions, 150 VIP Coins. -->
		<set name="icon" val="BranchIcon.Icon.etc_vip_present_i06" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="FISH" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="extractableCountMin" val="3" />
		<set name="extractableCountMax" val="3" />
		<capsuled_items>
			<item id="91689" min="1" max="1" chance="100.00" /> <!-- Blessed Scroll of Escape -->
			<item id="3936" min="1" max="1" chance="100.00" /> <!-- Blessed Scroll of Resurrection -->
			<item id="29652" min="3" max="3" chance="100.00" /> <!-- Major Healing Potion -->
		</capsuled_items>
	</item>
	<item id="99029" name="Daily Present - VIP 10" type="EtcItem">
		<!-- Double-click the item to receive 1 Blessed Scroll of Escape, 1 Blessed Scroll of Resurrection, 3 Greater Healing Potions, 150 VIP Coins. -->
		<set name="icon" val="BranchIcon.Icon.etc_vip_present_i06" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="FISH" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="extractableCountMin" val="3" />
		<set name="extractableCountMax" val="3" />
		<capsuled_items>
			<item id="91689" min="1" max="1" chance="100.00" /> <!-- Blessed Scroll of Escape -->
			<item id="3936" min="1" max="1" chance="100.00" /> <!-- Blessed Scroll of Resurrection -->
			<item id="29652" min="3" max="3" chance="100.00" /> <!-- Major Healing Potion -->
		</capsuled_items>
	</item>
</list>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_Essence_6.0_BattleChronicle/dist/game/data/stats/items/45500-45599.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="45584" name="Mark of Battle" additionalName="Sealed" type="EtcItem">
		<!-- A reward for the Olympiad achievements. Can be traded for a special gift by Olympiad Managers in any village. -->
		<set name="icon" val="icon.bel_mark_clear" />
		<set name="material" val="CRYSTAL" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
	</item>
</list>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_Essence_6.0_BattleChronicle/dist/game/data/stats/items/30300-30399.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="30372" name="Hero's Cloak" additionalName="Sealed" type="Armor">
		<!-- Max HP/ MP/ CP +10%, P. Def. +5%, M. Def. +10%, Resistance to All Weapons +5%, P. Critical Rate/ M. Skill Critical Rate +20, Received PvP Damage -10%, Damage Reflection +4%. -->
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="immediate_effect" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
		<skills>
			<skill id="13136" level="1" /> <!-- Hero's Cloak -->
		</skills>
	</item>
	<item id="30373" name="Glorious Cloak" additionalName="Sealed" type="Armor">
		<!-- Max HP/ MP/ CP +10%, P. Def. +5%, M. Def. +10%, Resistance to All Weapons +5%, P. Critical Rate/ M. Skill Critical Rate +20, Received PvP Damage -10%, Damage Reflection +4%. -->
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="immediate_effect" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
	</item>
</list>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_Essence_6.0_BattleChronicle/dist/game/data/stats/items/21500-21599.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="21566" name="Valkyrie Circlet" additionalName="Event" type="Armor">
		<!-- A circlet holding Valkyrie's strength. Occupies 2 Hair Accessory slots. Cannot be exchanged, dropped, destroyed, or sold. Can be stored in private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_valkyrie_cap_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_freightable" val="true" />
	</item>
</list>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_Essence_6.0_BattleChronicle/dist/game/data/stats/items/20000-20099.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="20020" name="Uniform Hat" additionalName="Not Available" type="Armor">
		<!-- A very fancy hat. Occupies 2 Hair Accessory slots. -->
		<set name="icon" val="BranchSys.icon.br_Uniform_Hat_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_sellable" val="false" />
	</item>
	<item id="20021" name="Assassin's Bamboo Hat" additionalName="Not Available" type="Armor">
		<!-- A hat made from bulrush. Occupies 2 Hair Accessory slots. -->
		<set name="icon" val="BranchSys.icon.br_Bamboo_Hat_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_sellable" val="false" />
	</item>
	<item id="20022" name="Ruthless Tribe Mask" additionalName="Not Available" type="Armor">
		<!-- A mask which formerly belonged to Looters. -->
		<set name="icon" val="BranchSys.icon.br_mask_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_sellable" val="false" />
	</item>
	<item id="20023" name="Ribbon Hairband" additionalName="Not Available" type="Armor">
		<!-- A ribbon-like hair accessory, intended for female characters only. -->
		<set name="icon" val="BranchSys.icon.br_Ribbon_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_sellable" val="false" />
	</item>
	<item id="20033" name="My Teleport Flag" type="EtcItem">
		<!-- The item is used when the current location of an Unoccupied Teleport Device is saved. -->
		<set name="icon" val="BranchSys.icon.br_flag_of_bookmark_i00" />
		<set name="material" val="PAPER" />
		<set name="weight" val="5" />
		<set name="is_stackable" val="true" />
		<set name="is_freightable" val="true" />
	</item>
</list>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_Essence_6.0_BattleChronicle/dist/game/data/stats/items/21700-21799.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="21713" name="Zaken's Sealed Cloak" type="EtcItem">
		<!-- Increases HP when the seal is released. -->
		<set name="icon" val="icon.sealed_vesper_cloack_i01" />
		<set name="weight" val="220" />
		<set name="price" val="29674485" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="material" val="CLOTH" />
	</item>
	<item id="21716" name="Zaken's Cloak" type="Armor">
		<!-- A cloak that makes you feel Zaken's sorrow. Max HP +5%. -->
		<set name="icon" val="BranchSys2.Icon.br_zaken_cloak_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<set name="price" val="29674485" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="handler" val="ItemSkills" />
		<skills>
			<skill id="45020" level="1" /> <!-- Zaken's Cloak -->
		</skills>
	</item>
	<item id="21754" name="Server Master Magic Pencil" type="Weapon">
		<!-- Magic on the tip of a pencil. A special item for the Head of the server. -->
		<set name="icon" val="BranchSys2.icon.g_pencil_of_servermaster" />
		<set name="default_action" val="EQUIP" />
		<set name="weapon_type" val="POLE" />
		<set name="bodypart" val="lrhand" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="BRONZE" />
		<set name="weight" val="100" />
		<set name="soulshots" val="1" />
		<set name="spiritshots" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<skills>
			<skill id="3599" level="1" /> <!-- Polearm Multi-attack -->
		</skills>
		<stats>
			<stat type="pAtk">1</stat>
			<stat type="rCrit">8</stat>
			<stat type="pAtkSpd">325</stat>
			<stat type="randomDamage">1</stat>
			<stat type="pAtkRange">80</stat>
		</stats>
	</item>
	<item id="21755" name="The Best Graduate's Cope" type="Armor">
		<!-- A Cope with Golden Tassel symbolizing wisdom. -->
		<set name="icon" val="BranchSys2.icon.g_graduation_cap_gold" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
	</item>
</list>
