=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_10.0_MasterClass/dist/game/data/xsd/items.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="item">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element maxOccurs="unbounded" name="set">
									<xs:complexType>
										<xs:attribute name="name" type="xs:string" use="required" />
										<xs:attribute name="val" type="xs:string" use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element maxOccurs="unbounded" name="cond">
									<xs:complexType>
										<xs:sequence>
											<xs:element minOccurs="0" name="target">
												<xs:complexType>
													<xs:attribute name="levelRange" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="and">
												<xs:complexType>
													<xs:sequence>
														<xs:element maxOccurs="unbounded" name="player">
															<xs:complexType>
																<xs:attribute name="castle" type="xs:byte" use="optional" />
																<xs:attribute name="pledgeClass" type="xs:byte" use="optional" />
																<xs:attribute name="races" type="xs:string" use="optional" />
																<xs:attribute name="clanHall" type="xs:byte" use="optional" />
																<xs:attribute name="isHero" type="xs:boolean" use="optional" />
																<xs:attribute name="categoryType" type="xs:string" use="optional" />
																<xs:attribute name="subclass" type="xs:boolean" use="optional" />
																<xs:attribute name="level" type="xs:unsignedByte" use="optional" />
																<xs:attribute name="cloakStatus" type="xs:boolean" use="optional" />
																<xs:attribute name="instanceId" type="xs:string" use="optional" />
																<xs:attribute name="isOnSide" type="xs:string" use="optional" />
																<xs:attribute name="isClanLeader" type="xs:boolean" use="optional" />
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="player">
												<xs:complexType>
													<xs:attribute name="flyMounted" type="xs:boolean" use="optional" />
													<xs:attribute name="categoryType" type="xs:string" use="optional" />
													<xs:attribute name="isHero" type="xs:boolean" use="optional" />
													<xs:attribute name="sex" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="pkCount" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="pledgeClass" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="level" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="races" type="xs:string" use="optional" />
													<xs:attribute name="clanHall" type="xs:string" use="optional" />
													<xs:attribute name="castle" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="SiegeZone" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="fort" type="xs:byte" use="optional" />
													<xs:attribute name="chaotic" type="xs:boolean" use="optional" />
													<xs:attribute name="instanceId" type="xs:string" use="optional" />
													<xs:attribute name="cloakStatus" type="xs:boolean" use="optional" />
													<xs:attribute name="levelRange" type="xs:string" use="optional" />
													<xs:attribute name="insideZoneId" type="xs:string" use="optional" />
													<xs:attribute name="vehicleMounted" type="xs:boolean" use="optional" />
													<xs:attribute name="MinimumVitalityPoints" type="xs:unsignedShort" use="optional" />
													<xs:attribute name="class_id_restriction" type="xs:string" use="optional" />
													<xs:attribute name="symbolsealpoints" type="xs:unsignedShort" use="optional" />
													<xs:attribute name="MaximumVitalityPoints" type="xs:unsignedInt" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="addName" type="xs:unsignedByte" use="optional" />
										<xs:attribute name="msgId" type="xs:unsignedShort" use="optional" />
									</xs:complexType>
								</xs:element>
								<xs:element name="capsuled_items">
									<xs:complexType>
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="item">
												<xs:complexType>
													<xs:attribute name="id" type="xs:unsignedInt" use="required" />
													<xs:attribute name="min" type="xs:unsignedInt" use="required" />
													<xs:attribute name="max" type="xs:unsignedInt" use="required" />
													<xs:attribute name="chance" type="xs:decimal" use="required" />
													<xs:attribute name="minEnchant" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="maxEnchant" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="skills">
									<xs:complexType>
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="skill">
												<xs:complexType>
													<xs:attribute name="id" type="xs:unsignedShort" use="required" />
													<xs:attribute name="level" type="xs:unsignedByte" use="required" />
													<xs:attribute name="type" type="xs:string" use="optional" />
													<xs:attribute name="type_value" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="type_chance" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="stats">
									<xs:complexType mixed="true">
										<xs:sequence minOccurs="0">
											<xs:element maxOccurs="unbounded" name="stat">
												<xs:complexType>
													<xs:simpleContent>
														<xs:extension base="xs:float">
															<xs:attribute name="type" type="xs:string" use="required" />
														</xs:extension>
													</xs:simpleContent>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedInt" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="type" type="xs:string" use="required" />
						<xs:attribute name="additionalName" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Qvinticom/L2J_MOBIUS-2022/L2J_Mobius_6.0_Fafurion/dist/game/data/stats/items/29000-29099.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="29000" name="Scorpio Agathion Charm From the Star" additionalName="Stage 4" type="Armor">
		<!-- A charm that activates the power of the Scorpio Agathion.Combine with Starlight Jar up to Stage 12, and upgrade to +10 by using Book of Growth. Its special ability is Scorpion's Mass Exile Lv. 4, and depending on the level of the charm, a unique ability will be added. When equipped on the main slot of the Agathion Bracelet, the Agathion will be summoned automatically, and both special and unique abilities will be activated. When equipped on the sub slot, only the unique ability will be activated. <Note>When combining, the growth value of the Agathion Charm will be reset. -->
		<set name="icon" val="BranchIcon.icon.g_bm_sco_agathion_charm" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="R" />
		<set name="material" val="LEATHER" />
		<set name="weight" val="510" />
		<set name="enchant_enabled" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
	</item>
	<item id="29001" name="Scorpio Agathion Charm From the Star" additionalName="Stage 5" type="Armor">
		<!-- A charm that activates the power of the Scorpio Agathion.Combine with Starlight Jar up to Stage 12, and upgrade to +10 by using Book of Growth. Its special ability is Scorpion's Mass Exile Lv. 5, and depending on the level of the charm, a unique ability will be added. When equipped on the main slot of the Agathion Bracelet, the Agathion will be summoned automatically, and both special and unique abilities will be activated. When equipped on the sub slot, only the unique ability will be activated. <Note>When combining, the growth value of the Agathion Charm will be reset. -->
		<set name="icon" val="BranchIcon.icon.g_bm_sco_agathion_charm" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="lhand" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="R" />
		<set name="material" val="LEATHER" />
		<set name="weight" val="1070" />
		<set name="enchant_enabled" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
	</item>
	<item id="29002" name="Scorpio Agathion Charm From the Star" additionalName="Stage 6" type="Armor">
		<!-- A charm that activates the power of the Scorpio Agathion.Combine with Starlight Jar up to Stage 12, and upgrade to +10 by using Book of Growth. Its special ability is Scorpion's Mass Exile Lv. 6, and depending on the level of the charm, a unique ability will be added. When equipped on the main slot of the Agathion Bracelet, the Agathion will be summoned automatically, and both special and unique abilities will be activated. When equipped on the sub slot, only the unique ability will be activated. <Note>When combining, the growth value of the Agathion Charm will be reset. -->
		<set name="icon" val="BranchIcon.icon.g_bm_sco_agathion_charm" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="head" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="R" />
		<set name="material" val="BONE" />
		<set name="weight" val="530" />
		<set name="enchant_enabled" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
	</item>
	<item id="29003" name="Scorpio Agathion Charm From the Star" additionalName="Stage 7" type="Armor">
		<!-- A charm that activates the power of the Scorpio Agathion.Combine with Starlight Jar up to Stage 12, and upgrade to +10 by using Book of Growth. Its special ability is Scorpion's Mass Exile Lv. 7, and depending on the level of the charm, a unique ability will be added. When equipped on the main slot of the Agathion Bracelet, the Agathion will be summoned automatically, and both special and unique abilities will be activated. When equipped on the sub slot, only the unique ability will be activated. <Note>When combining, the growth value of the Agathion Charm will be reset. -->
		<set name="icon" val="BranchIcon.icon.g_bm_sco_agathion_charm" />
		<set name="default_action" val="EQUIP" />
		<set name="armor_type" val="MAGIC" />
		<set name="bodypart" val="hair2" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="R" />
		<set name="material" val="BRONZE" />
		<set name="weight" val="1750" />
		<set name="enchant_enabled" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
		<stats>
			<stat type="maxMp">649</stat>
		</stats>
	</item>
	<item id="29004" name="Scorpio Agathion Charm From the Star" additionalName="Stage 8" type="Armor">
		<!-- A charm that activates the power of the Scorpio Agathion.Combine with Starlight Jar up to Stage 12, and upgrade to +10 by using Book of Growth. Its special ability is Scorpion's Mass Exile Lv. 8, and depending on the level of the charm, a unique ability will be added. When equipped on the main slot of the Agathion Bracelet, the Agathion will be summoned automatically, and both special and unique abilities will be activated. When equipped on the sub slot, only the unique ability will be activated. <Note>When combining, the growth value of the Agathion Charm will be reset. -->
		<set name="icon" val="BranchIcon.icon.g_bm_sco_agathion_charm" />
		<set name="default_action" val="EQUIP" />
		<set name="armor_type" val="MAGIC" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="R" />
		<set name="material" val="SCALE_OF_DRAGON" />
		<set name="weight" val="850" />
		<set name="enchant_enabled" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
		<stats>
			<stat type="maxMp">427</stat>
		</stats>
	</item>
	<item id="29005" name="Scorpio Agathion Charm From the Star" additionalName="Stage 9" type="Armor">
		<!-- A charm that activates the power of the Scorpio Agathion.Combine with Starlight Jar up to Stage 12, and upgrade to +10 by using Book of Growth. Its special ability is Scorpion's Mass Exile Lv. 9, and depending on the level of the charm, a unique ability will be added. When equipped on the main slot of the Agathion Bracelet, the Agathion will be summoned automatically, and both special and unique abilities will be activated. When equipped on the sub slot, only the unique ability will be activated. <Note>When combining, the growth value of the Agathion Charm will be reset. -->
		<set name="icon" val="BranchIcon.icon.g_bm_sco_agathion_charm" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hair" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="R" />
		<set name="material" val="LEATHER" />
		<set name="weight" val="510" />
		<set name="enchant_enabled" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
	</item>
	<item id="29006" name="Scorpio Agathion Charm From the Star" additionalName="Stage 10" type="Armor">
		<!-- A charm that activates the power of the Scorpio Agathion.Combine with Starlight Jar up to Stage 12, and upgrade to +10 by using Book of Growth. Its special ability is Scorpion's Mass Exile Lv. 10, and depending on the level of the charm, a unique ability will be added. When equipped on the main slot of the Agathion Bracelet, the Agathion will be summoned automatically, and both special and unique abilities will be activated. When equipped on the sub slot, only the unique ability will be activated. <Note>When combining, the growth value of the Agathion Charm will be reset. -->
		<set name="icon" val="BranchIcon.icon.g_bm_sco_agathion_charm" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="lhand" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="R" />
		<set name="material" val="LEATHER" />
		<set name="weight" val="1070" />
		<set name="enchant_enabled" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
	</item>
	<item id="29007" name="Scorpio Agathion Charm From the Star" additionalName="Stage 11" type="Armor">
		<!-- A charm that activates the power of the Scorpio Agathion.Combine with Starlight Jar up to Stage 12, and upgrade to +10 by using Book of Growth. Its special ability is Scorpion's Mass Exile Lv. 11, and depending on the level of the charm, a unique ability will be added. When equipped on the main slot of the Agathion Bracelet, the Agathion will be summoned automatically, and both special and unique abilities will be activated. When equipped on the sub slot, only the unique ability will be activated. <Note>When combining, the growth value of the Agathion Charm will be reset. -->
		<set name="icon" val="BranchIcon.icon.g_bm_sco_agathion_charm" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="head" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="R" />
		<set name="material" val="BONE" />
		<set name="weight" val="530" />
		<set name="enchant_enabled" val="1" />
